name: Angular Value Flash deploy compodoc
on:
  push:
    branches:
      - compodoc
jobs:
  publish-compodoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Compodocs
        run: npm run docs
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: documentation
